# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "El blog de Nubart"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Nubart es la audioguía que te puedes llevar. En este blog te hablaremos de museos, de soluciones tecnológicas, de nuestras exposiciones y de nuestro anecdotario cotidiano."

# Tagline near the site title
tagline: "La audioguía que te puedes llevar"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: /blog

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://www.nubart.eu"

# Site navigation - each item must have a title and a url.
navigation:
- text: Inicio
  url: /
- text: Web
  url: http://www.nubart.eu/
- text: Archivo
  url: /etiquetas/

# The shortname for your Disqus site to enable comments.
disqus: "nubart"

# Author information - author info at the bottom of the post
author_name: "Rosa"
author_bio: "Rosa es la co-fundadora de Digital Tangible SL, la empresa que ideó Nubart."
author_image: /images/rosa-sala.jpg

# Sidebar Add banner
banner_url: "http://www.nubart.eu/"
banner_image: images/muestra-audioguia-nubart-con-auriculares.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//seebook.us7.list-manage.com/subscribe/post?u=b630182f489a9aa406cb122cf&amp;id=7ebd16ce5e"


# Social links in the site footer
twitter_username: "nub_art"
instagram_username: "_nubart"
facebook_username: "Nubart"
linkedin_username: "nubart"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
